export const SET_QUERY = 'SET_QUERY'
export const FETCH_RESULTS = 'FETCH_RESULTS'; 
export const FETCH_RESULTS_FAIL = 'FETCH_RESULTS_FAIL'; 

export const NOMINATE_MOVIE = 'NOMINATE_MOVIE'; 
export const DELETE_NOMINATION = 'DELETE_NOMINATION';
export const HIDE_BANNER = 'HIDE_BANNER';